# Generated by Django 5.0.6 on 2024-07-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='game_status',
            field=models.CharField(choices=[('n', 'New'), ('a', 'Active'), ('o', 'Offline')], default='l', max_length=1),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_ping_latency',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
