# Generated by Django 5.0.6 on 2024-07-11 03:19

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_server_game_status_alter_server_last_ping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('location', models.CharField(max_length=240)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('last_ping_latency', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('n', 'Joining'), ('l', 'In Lobby'), ('p', 'Playing'), ('s', 'Spectating')], default='n', max_length=1)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='host.region')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'unique_together': {('user', 'server')},
            },
        ),
    ]
